# Local development profile - uruchamianie bez Dockera
# Wymaga lokalnie uruchomionej bazy PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/easyapply_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Pokazuj SQL w trybie lokalnym
spring.jpa.show-sql=true

# Flyway
spring.flyway.clean-disabled=false
